XhatGpt/ChatGppt/ChatGppt/urls.py
from django.contrib import admin
from django.urls import path,include
from xhatapp import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.login_usr,name='indexpage'),
    # path('login',views.login_usr,name="llooggin"),
    path('Xhat/',include('xhatapp.urls')),
    path("check",views.query,name="xhat"),
    path('Signin',views.create,name='createeacc'),
    path('logout',views.usr_logout,name="logggout")
]

XhatGpt/ChatGppt/xhatapp/urls.py
from django.urls import path
from . import views

app_name = 'xhatapp'

urlpatterns = [
    path('',views.query,name="xhatgpt"), # can use name for link refering, 'xhatgpt:xhatgpt'
    path('About',views.about,name="aboutx"), # 'xhatgpt:aboutx'
]

# take logo frm https://arcane.com/en-gb/

XhatGpt/ChatGppt/xhatapp/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User
# from datetime import date
# Create your models here.

class SaveQueries(models.Model):
    question = models.CharField(null=False,max_length=2800) # jst limiting !!
    returnquery = models.CharField(null=False,max_length=35000)
    query_time = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.question + " " + self.returnquery


class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

XhatGpt/ChatGppt/xhatapp/views.py
from django.shortcuts import render
from xhatapp.models import SaveQueries
from xhatapp.Config import BravoSis
from xhatapp.form import usserform
# from datetime import datetime 
from django.utils import timezone
# Create your views here.


###################### -login
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# initializing 
wow = BravoSis()
# wow.ai(query)

# Client for telegram
# LeosBot = Client(name="XhatGpt",api_id=wow.api_id,api_hash=wow.api_hash)

def index(request):
    return render(request, 'xhatapp/index.html')

def about(request):
    return render(request, 'xhatapp/about.html')

@login_required
def query(request):
    nice = "Do you have a question you'd like me to answer?"
    result = "....."
    if request.method == 'POST':
        nice = request.POST.get('queryinput')
        print(nice)
        result = wow.ai(nice) #added new key # !--working but... Quata Exousted!
        print(result)
        # add if result is Quata Exausted later...
        # else 'ss' & 'send msg to db channel'
        ss = SaveQueries(question=nice,returnquery=result,query_time=timezone.now()) #need to check if this is working 
        ss.save()
        tim = timezone.now()
        # my_result_dict = SaveQueries.objects.order_by('-query_time')
        print(tim)
        # print(my_result_dict)
        # for data in my_result_dict:
        #     print(data.question)
        #     print(data.returnquery)
        #     print(data.query_time)
        # my_result_dict = {'query':nice,'resul':result}

    # return render(request, 'xhatapp/index.html', context=my_result_dict)
    return render(request, 'xhatapp/index.html',{'query':nice,'resul':result})


def create(request):
    acc_created = False

    if request.method == 'POST':
        usr_form = usserform(data=request.POST)

        if usr_form.is_valid():
            user = usr_form.save()
            user.set_password(user.password)
            user.save()

            acc_created = True
        else:
            print(usr_form.errors)
    
    else:
        usr_form = usserform()

    return render(request, 'xhatapp/createacc.html',{"acc_form":usr_form,"created":acc_created})


def login_usr(request):
    if request.method == 'POST':
        usrname = request.POST.get('Username')
        passwrd = request.POST.get('passsw')
        print(usrname,passwrd)

        user = authenticate(username=usrname, password=passwrd)

        if user:
            if user.is_active:
                login(request, user)
                print("checkked")
                return HttpResponseRedirect(reverse('xhat'))
          
            else:
                print("Account not usable...")
                return HttpResponse("Account not usable...")
        else:
            print(f"""
                somone tried to login!!!
                username : {usrname}
                password : {passwrd}
                """)
            return HttpResponse("OOpppzz Invalid Login Details....")
    else:
        return render(request, 'xhatapp/login.html')

@login_required
def usr_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('indexpage'))

XhatGpt/ChatGppt/templates/xhatapp/about.html
{% extends 'xhatapp/base.html' %}

{% block body_block%}
<div class="container">
    <div class="card text-bg-dark mb-3" style="height: 25rem;">
        <div class="card-body">
            <!-- can set this on about page -->
            <h1 class="card-title">About - XhatGpt</h1>
            <p style="color: #B8336A;" class="card-text"><marquee>!!! XhatGpt is using official OpenAi API So,Please don't spam!!!</marquee></p>
            <p class="card-text" id="myText2">XhatGpt works same as ChatGpt, Which is using free tier - only created this project for Educational purpose. It will help to reduce the difficulty traffic of ChatGpt.</p>
            <p class="card-text">(Open Source :<a href=""> Check Github</a>)</p>
            <!-- <p class="card-text" id="typing-text"></p> -->
        </div>
    </div>
</div>
{% endblock %}

XhatGpt/ChatGppt/templates/xhatapp/base.html
<!doctype html>
<html lang="en">

<head>
  <title>XhatGpt</title>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- send button !--  -->
</head>

<body class="text-bg-secondary">
  <header>
    <!-- nav one -->
    <nav class="navbar navbar-expand-sm navbar-light bg-darklight">
          <div class="container">
            <a class="navbar-brand" href="{% url 'xhat' %}">XhatGpt</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'xhatapp:aboutx' %}" aria-current="page">About <span class="visually-hidden">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logggout' %}">Log out</a>
                  </li>
                </ul>
            </div>
      </div>
    </nav>
    <!-- Sec nav -->
    <nav class="navbar navbar-expand-sm navbar-light text-bg-secondary fixed-bottom">
        <div class="container">
          <!-- <a class="navbar-brand" href="#">ChatGpt</a> -->
            <div class="card text-bg-dark" style="width: 100%";>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="input-group mb-0 pb-0">
                            <input type="text" name="queryinput" class="form-control text-bg-dark" placeholder="Send a message...">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
                                    <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
                                  </svg></button>
                            </div>
                        </div>
                    </form>
                </div>
                    <a align="center" class="link-underline-light" href="https://github.com/Roshan-Here">&copy; <strong><span>Roshan-Here</span></strong></a>
            </div>
        </div>
    </nav>
  </header>
  <!-- block here -->
  <main class="mt-3">
    <!-- 1 checking -->
    {% block body_block %}
    {% endblock %}
        <!-- 2 checking -->
        <!-- <div class="container">
            <div class="card text-bg-dark mb-3" style="height: 25rem;">
                <div class="card-body">
                    <h1 class="card-title">XhatGpt</h1>
                    <p class="card-text" id="myText">its me leo....</p>
                </div>
            </div>
        </div> -->
  </main>
  <!-- upto block -->
  <footer class="footer mt-auto py-3 bg-secondary">
        <!-- <div class="container">
            <div class="card">
                <div class="card-body">
                <form>
                <div class="input-group mb-0">
                    <input type="text" class="form-control text-bg-dark" placeholder="Type your message here...">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Send</button>
                    </div>
                </div>
                </form>
                </div>
            </div>
        </div> -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>

<!-- Mov- this -to- JavaScript  -->
<script>   
  const text = document.getElementById("myText2").textContent;
    let i = 0;
  
    function typeText() {
      if (i < text.length) {
        document.getElementById("myText2").innerHTML = text.substring(0, i) + "|";
        i++;
        setTimeout(typeText, 20); // Adjust the typing speed here
      } else {
        document.getElementById("myText2").innerHTML = text;
      }
    }
  
    typeText();
</script>
<!-- End- this -to- JavaScript  -->


</body>

</html>

XhatGpt/ChatGppt/templates/xhatapp/createacc.html
<!doctype html>
<html lang="en">

<head>
  <title>XhatGpt</title>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body class="text-bg-secondary">
    <header>
      <nav class="navbar navbar-light bg-secondary fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
              <img src="https://arcane.com/static/arcane-logo-r-c5c6e8cc377f92f125e50baf52988a87.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">XhatGpt
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header bg-secondary">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">XhatGpt</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body bg-secondary">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <div class="offcanvas-body">
                    <div>
                      <div class="col-sm-12">
                          <img src="https://arcane.com/static/arcane-logo-r-c5c6e8cc377f92f125e50baf52988a87.png" class="img-fluid rounded-top float-start" alt="">
                      </div>
                      <!-- Hover added -->
                    </div>
                </div>
                <!-- <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li> -->
                
                <div class="container">
                    <div class="list-group">
                        <a href="https://github.com/Roshan-Here" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Github</a>
                        <a href="https://tx.me/Xequisting" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Telegram</a>
                        <a href="mailto:muhammedroshanps@gmail.com" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Email</a>
                    <!-- add linkdin button -->
                    </div>
                </div>

                <!-- <li class="nav-item">
                  <a class="nav-link" href="#">Home</a>
                </li> -->
              </ul>
            </div>
          </div>
        </div>
      </nav>  
</header>
<main class="mt-3">
    <br>
    <br>
    <div class="container">
      <br>
      <br>
        <div class="row">
            <div class="col-md-6 mx-auto text-bg-dark mb-3" style="height: 100%; width: 50; border-radius: 5%;">
              <br>
                <div class="card-body">
                    {% if created %}
                    <h3>Already registed Back to login....</h3>
                    <a name="" id="" class="btn btn-info" href="{% url 'indexpage' %}" role="button">Login..</a>
                    <br>
                    {% else %}
                        <form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            {{ acc_form.as_p }}
                            <input type="submit" value="Create Account">
                        </form>
                        <div class="mb-3">
                        <form action="{% url 'indexpage' %}">
                        <a>Go to Login page :</a>
                        <input style="margin-left: 4%;" name="" id="" class="btn btn-info" type="submit" value="Login">
                      </form>
                      </div>
                    {% endif %}
                    <br>
                </div>
            </div>
        </div>
    </div>
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

XhatGpt/ChatGppt/templates/xhatapp/index.html
{% extends 'xhatapp/base.html' %}

{% block body_block %}
<div class="container" style="height: 100%;">
    <div class="card text-bg-dark mb-3" style="height: 100%;">
        <div class="card-body">
            <!-- need to add user name, in Q -->
            <h4 class="card-title">Q:- {{ query }} </h4>
            <button style="margin-left: 90%;" class="btn btn-light btn-sm" onclick="copyToClipboard(this)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-clipboard" viewBox="0 0 16 16">
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                    <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                  </svg>
            </button>
            <p class="card-text" id="myText">{{ resul }}</p>
        </div>
    </div>
</div>

<script>
    var myParagraph = document.getElementById("myText"); 
    var originalText = myParagraph.innerHTML;
    var newText = originalText.replace(/\s{2,}/g, "<br>"); //-replace every third space with line break
    myParagraph.innerHTML = newText;

    function copyToClipboard(button) {
      const cardText = button.parentNode.querySelector(".card-text").textContent;
      const tempElement = document.createElement("textarea");
      tempElement.value = cardText;
      document.body.appendChild(tempElement);
      tempElement.select();
      document.execCommand("copy");
      document.body.removeChild(tempElement);
    }

    const text = newText;
    let i = 0;
  
    function typeText() {
      if (i < text.length) {
        document.getElementById("myText").innerHTML = text.substring(0, i) + "|";
        i++;
        setTimeout(typeText, 20); // Adjust the typing speed here
      } else {
        document.getElementById("myText").innerHTML = text;
      }
    }
  
    typeText();
</script>
{% endblock %}

XhatGpt/ChatGppt/templates/xhatapp/login.html
<!doctype html>
<html lang="en">

<head>
  <title>XhatGpt</title>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body class="text-bg-secondary">
    <header>
      <nav class="navbar navbar-light bg-secondary fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
              <img src="https://arcane.com/static/arcane-logo-r-c5c6e8cc377f92f125e50baf52988a87.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">XhatGpt
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header bg-secondary">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">XhatGpt</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body bg-secondary">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <div class="offcanvas-body">
                    <div>
                      <div class="col-sm-12">
                          <img src="https://arcane.com/static/arcane-logo-r-c5c6e8cc377f92f125e50baf52988a87.png" class="img-fluid rounded-top float-start" alt="">
                      </div>
                      <!-- Hover added -->
                    </div>
                </div>
                <!-- <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li> -->
                
                <div class="container">
                    <div class="list-group">
                        <a href="https://github.com/Roshan-Here" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Github</a>
                        <a href="https://tx.me/Xequisting" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Telegram</a>
                        <a href="mailto:muhammedroshanps@gmail.com" class="list-group-item list-group-item-action p-2 mb-1 bg-black text-white">Email</a>
                    <!-- add linkdin button -->
                    </div>
                </div>

                <!-- <li class="nav-item">
                  <a class="nav-link" href="#">Home</a>
                </li> -->
              </ul>
            </div>
          </div>
        </div>
      </nav>  
</header>
<main class="mt-3">
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-bg-dark mb-3" style="height: 100%; width: 50; border-radius: 5%;">
                <div class="card-body">
                    <!-- can set this on about page -->
                    <h1 align="center" class="card-title">Login Page</h1>
                    <p style="color: #B8336A;" class="card-text"><marquee>!!! XhatGpt is using official OpenAi API So,Please don't spam!!!</marquee></p>
                    <!-- <p class="card-text" id="myText">XhatGpt with telegram database channel support, need a telegram bot token, telegram api, Pyrogram preinstalled and mainly OpenAi API Key: which will fetch results</p> -->
                    <div class="mb-3">
                    <form action="{% url 'indexpage' %}" method="POST">
                    {% csrf_token %}
                    <label for="Username" class="form-label">Username:</label>
                    <input type="text"
                        class="form-control" name="Username" id="" aria-describedby="helpId" placeholder="User Name">
                    <!-- <small id="helpId" class="form-text text-muted"></small> -->
                        <div class="mb-3">
                        <label for="passsw" class="form-label">Password</label>
                        <input name="passsw" type="password" class="form-control" id="" placeholder="Enter Password">
                        <a style="margin-left: 2%;" href="{% url 'createeacc' %}"> Create Account</a>
                        <input style="margin-left: 18%; margin-top: 2%;" name="" id="" class="btn btn-info" type="submit" value="Login">
                      </div>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>